### PR TITLE
Support foreign key checks

### PR DESCRIPTION
**Pull request by roll**
- improved `validate`
- connects https://github.com/frictionlessdata/datapackage-py/issues/150

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
Please take a look. It's a straight port of https://github.com/frictionlessdata/tableschema-js/pull/88 but may be it makes sense to review this one first because there is no noise.

**Comment by roll** [comment]
@amercader 
Yes. On `tableschema` level we expect lookup table in `references` argument. And on `datapackage` level we create this lookup table - https://github.com/frictionlessdata/datapackage-py/pull/153. 

Sorry I've added more comments to JavaScript PR (https://github.com/frictionlessdata/tableschema-js/pull/88) but forget to clarify where to find it.

**Comment by roll** [comment]
So as a user I actually will be using it like this - https://github.com/frictionlessdata/datapackage-py/pull/153/files#diff-ed1e95b24fbf90fddd0edfbc46764fadR895 (on `datapackage` level)

**Comment by amercader** [comment]
@roll that makes much more sense, thanks

**Pull request merged**
