### PR TITLE
[BREAKING] Drop deprecated for v1 API

### PR DESCRIPTION
**Pull request by roll**
- connects #80 
  - removed all inactive code
  - cleaned public API

### CODE REVIEW

**Comment by roll** [comment]
@pwalsh 
please review - I was working on JSON schema v1 integration but inactive code was blocking

**Comment by roll** [comment]
@pwalsh 
It's blocking so please review if needed after merge (it's just a mechanical removal of inactive code and deprecated API which has been deprecated much time ago).

**Comment by pwalsh** [comment]
How is it blocking v1? I'm approving but it is already merged anyway.

**Comment by roll** [comment]
It was blocking my work on integration of v1 JSON schema for Table Schema. There was a few users of `validate` like `model.SchemaModel`. Much faster was to drop it instead of implementing changes in two places to pass tests.

**Pull request merged**
