### PR TITLE
Fix inferring algorithm, make sure to choose the lowest common denominator

### LINKED ISSUE #209: Infer bad type
Hi guys,

I just discovered this project, and I met one strange problem while reading a CSV file, hope you can help about that :

Python code :

```python
#!/bin/env python3

from tabulate import tabulate
from tableschema import Table


table = Table("bug.csv")

table.infer()

print(tabulate(table.schema.descriptor['fields'], headers="keys", tablefmt="pipe"))

try:
    table.read(keyed=False, cast=True)
except Exception as err:
    print(err.errors)
    exit(1)
```

bug.csv(v1):
```csv
id,lenght
1,456
2,456.2
```
bug.csv(v2):
```csv
id,lenght
1,456
2,456.2
3,456
```

When using the v1 file, result are as expected, wereas when using the v2 file, something strange happend, please see..

v1:
```bash
$ python3 bug.py 
| name   | type    | format   |
|:-------|:--------|:---------|
| id     | integer | default  |
| lenght | number  | default  |
```

v2:
```bash
$ python3 bug.py 
| name   | type    | format   |
|:-------|:--------|:---------|
| id     | integer | default  |
| lenght | integer | default  |

[CastError('Field "lenght" can\'t cast value "456.2" for type "integer" with format "default"',)]
```

There are, for me, two problems :
- first, why is the first working whereas the second is not ? (why number type became integer ?)
- and then, wouldn't it be easier, for the sake of the initial data, to take the more 'permissive' type, here integer, instead of those that seems represent the majority ?

I reproduce this bug from the reading an csv file of 25k lines, whereas about 25% of lines match this problem ..

I try to use tableschema for an automatic insertion of csv files into a database, with auto-matching types on remote database, without human interactions, so that kind of problem is really problematic, i met it on 2 of the 4 csv files I tested.

Hope you can help

### LINKED ISSUE #210: Types are wrongly inferred
```
$ python
>>> open('test.csv', 'w').write('\n'.join(['not-an-int','1','2','3','4','dog']))
22
>>> from tableschema import Table
>>> t=Table('test.csv')
>>> t.infer()
{'fields': [{'name': 'not-an-int', 'type': 'integer', 'format': 'default'}], 'missingValues': ['']}
```

The `not-an-int` column should have been inferred as a `string`, but instead it got `integer`.

### PR DESCRIPTION
**Pull request by akariv**
- fixes #210
- fixes #209

---

The infer algorithm has a problem - for each sample value in each column, it tries to find the most specific type it can cast it to. Then it counts which type has the most occurrences.

As can be seen in the attached bug, this method is not correct. 

The PR changes the algorithm so it does not find just one type per value, but all applicable types.
Then the selected type is the one with most occurrences (and amongst those - the most specific type).

### CODE REVIEW

**Comment by roll** [comment]
@akariv 
Thanks.

Regarding the changes - I think we touch here the same thing we discussed with @Stephen-Gates and others on `tableschema-js`.

For example if we have a column like:
1
2
3
4
5
typo
7
8
9

I guess the updated algorithm will say it's a `string` but `tableschema-js` will say that it's an `integer` because it uses a probabilistic algorithm including the confidence concept (like `chardet`) based on the idea that `infer` is just a first iteration on a schema creation (requiring manual tweaks later). 

Not sure it's implemented already or not for `tableschema-js` but we were also looking for an option to get the lowest common denominator. List this:
```
schema = infer(data, confidence=1)  # should return `string` for our example
```
https://github.com/frictionlessdata/tableschema-js/blob/master/src/config.js#L5

So I'm kinda confused what we better to do with `tableschema-py` for now. Because these changes are switching the lib from one mode to another mode. And I can't say that any of this behavior is incorrect.

Maybe we try to start with confidence flag here? For example:
```
schema = infer(data) # work as before this PR
schema = infer(data, confidence=1) # switching to behaviour proposed in this PR
```

And later we just update the whole algo based on the `tableschema.js` lib (which is a way faster - https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L179) preserving proposed behavior for the client.

WDYT?

**Comment by akariv** [comment]
I think that infer schema should always return a schema that works with the data.
Anything else feels like a bug to me.

Allowing lower levels of confidence sounds like a great feature, but only as an addition over the basic functionality.

By the way, the current algorithm will return `integer` for the following list of values too:
  1,  
  1.2, 
  2, 
  2.3,  
  3,  
  3.4,   
  4

**Comment by akariv** [comment]
btw, implementing a 'confidence' parameter is super simple - just modify the sorting phase here:
https://github.com/frictionlessdata/tableschema-py/pull/211/files#diff-e7ea47bed4b0f96022a8553c5c1572ecR318

So that it takes all results with `count >= max(counts)*confidence` and picks the one with the highest `priority`.

**Comment by roll** [comment]
@akariv 
I would probably agree I think on the idea that `100% compliant` way should be default but historically the default way is `the best guess` (and in Python it doesn't work very well - not sure about JS for edge cases like above).

So I think we would better don't change the current default behavior to do not break the dependent software (esp. goodtables.io) and existent workflows (e.g. with CLI).

**Comment by akariv** [comment]
See my latest commit @roll - it now introduces a new confidence parameter, which defaults at 0.75 (which is inline with the current behaviour) but can also be set to 1.0 to make it strict.

**Comment by roll** [comment]
@akariv 
Cool. I think now it's just great

**Pull request merged**
