### PR TITLE
Fixed composite PK uniqueness check

### LINKED ISSUE #194: wrong interpretation of primaryKey forces unnecessary uniqueness constraints
```
$ python
Python 3.6.1 (default, Mar 27 2017, 00:25:54)
>>> import tableschema
>>> open("bla.csv", "w").write("""id1,id2,value
... a,a,1
... a,b,2
... b,a,3
... b,b,4
... """)
38
>>> t=tableschema.Table("bla.csv", schema={
... "fields":[{"name":"id1", "type":"string"}, {"name":"id2", "type":"string"}, {"name":"value","type":"integer"}], "primaryKey": ["id1", "id2"]})
<tableschema.table.Table object at 0x10ddfc898>
>>> it=t.iter()
>>> list(it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adam/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tableschema/table.py", line 102, in iter
    raise exceptions.CastError(message)
tableschema.exceptions.CastError: Field "id1" duplicates in row "3"
```

Since `id1` and `id2` are the primary key _together_, the uniqueness constraint should not be imposed on each one of these columns.

### PR DESCRIPTION
**Pull request by roll**
- fixes #194

### CODE REVIEW

**Comment by roll** [comment]
@akariv 
please take a look

**Comment by akariv** [comment]
The fix seems correct to me.
However, I wonder if it's the right way to go. For large datasets, this implementation would take lots of memory - especially for large primary keys. Performance wise, we will also see a degradation in large datasets as we move through the rows.

Because it can have these unwanted (and unexpected) side-effects, I would make this entire check  optional - that is, off by default.

**Comment by akariv** [comment]
Also - perhaps we could tie this in with the `strict` parameter?
At the moment I see that the `strict` parameter in the `Table` constructor is not used (is that on purpose?), so we can safely add that meaning to it (strict == extra validation checks, e.g. uniqueness).
wdyt?

**Comment by roll** [comment]
@akariv 
Thanks. I've moved the discussion to - https://github.com/frictionlessdata/tableschema-py/issues/196

**Pull request merged**
